{
 "title": "Portworx Perf Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "px_cluster_cpu_percent" },
   {
    "name": "Instances",
    "label": "Node",
    "query": "px_cluster_cpu_percent{cluster=\"$Cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Nodes and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(px_volume_halevel{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Alert List",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "{cluster=\"$Cluster\"}",
     "labelSelector": "alertname, issue, cluster, instance",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Attached volumes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_attached{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Storage Offline",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_status_nodes_storage_down{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Avg HA Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(px_volume_halevel {cluster=~\"$Cluster\"}) / count(px_volume_halevel{cluster=~\"$Cluster\"}))",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Total Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_total_bytes{cluster=~\"$Cluster\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Volume Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_usage_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Filesystem Total Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_volume_fs_usage_bytes{})"
    }
   ]
  },
  {
   "title": "IO Rate (Node Exporter)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m])) + sum(rate(node_disk_read_bytes_total{device=~\".+pxd.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Available",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "px_px_cache_total_blocks{cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Total Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "px_px_cache_used_blocks{cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Total Dirty",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "px_px_cache_dirty_blocks{cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "IO Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "px_px_cache_io_mbps{cluster=~\"$Cluster\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"$Cluster\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster=~\"$Cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Network Sent (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Network Received (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Storage Pending IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "rate(px_cluster_pendingio{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "expr": "rate(px_cluster_pendingio{cluster=~\"$Cluster\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Volume (Node Exporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Latency (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "- (rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "IOPS (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "-(rate(node_disk_reads_completed_total[1m])/rate(node_disk_read_time_seconds_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[1m])/rate(node_disk_write_time_seconds_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Throughput (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-(rate(node_disk_read_bytes_total[1m])/rate(node_disk_read_time_seconds_total[1m]))",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])/rate(node_disk_write_time_seconds_total[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "-(px_volume_vol_read_latency_seconds{})",
     "legendFormat": "{{node}}_{{volumeid}}"
    },
    {
     "expr": "px_volume_vol_write_latency_seconds{}",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "-(rate(px_disk_stats_num_reads[1m]))",
     "legendFormat": "{{node}}_{{device}}_read"
    },
    {
     "expr": "rate(px_disk_stats_num_writes[1m])",
     "legendFormat": "{{node}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-(rate(px_disk_stats_read_bytes_total[1m]))",
     "legendFormat": "{{node}}_{{disk}}_read"
    },
    {
     "expr": "rate(px_disk_stats_written_bytes_total[1m])",
     "legendFormat": "{{node}}_{{disk}}_write"
    }
   ]
  },
  {
   "title": "PX Vol IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "px_volume_iops{}", "legendFormat": "{{node}}_{{volumeid}}" }
   ]
  },
  {
   "title": "PX Vol Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "px_volume_readthroughput{}", "legendFormat": "{{node}}_{{volumeid}}_write" },
    { "expr": "-(px_volume_writethroughput{})", "legendFormat": "{{node}}_{{volumeid}}_write" }
   ]
  },
  {
   "title": "PX Vol Replica Flush Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(px_volume_replica_flush_ms_total[1m]) / rate(px_volume_replica_flushes_total[1m])",
     "legendFormat": "{{node}}_{{volumeid}}"
    }
   ]
  },
  {
   "title": "PX Vol Replica Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(px_volume_replica_written_bytes_total[1m]) / rate(px_volume_replica_write_ms_total[1m])",
     "legendFormat": "{{node}}_{{volumeid}}_write"
    },
    {
     "expr": "-(rate(px_volume_replica_read_bytes_total[1m]) / rate(px_volume_replica_read_ms_total[1m]))",
     "legendFormat": "{{node}}_{{volumeid}}_read"
    }
   ]
  },
  { "title": "Replica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "PX Pool Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_write_latency_seconds{}*1000",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "PX Pool Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_writethroughput{}",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "PX Vol Long Reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "px_volume_num_long_reads{}", "legendFormat": "{{node}}_{{volumeid}}" }
     ]
    },
    {
     "title": "PX Vol Long Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(px_volume_vol_written_bytes[1m]))"
      }
     ]
    },
    {
     "title": "PX Vol Long Flushes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "px_volume_num_long_flushes{}", "legendFormat": "{{node}}_{{volumeid}}" }
     ]
    }
   ]
  },
  {
   "title": "PX Pool Flush Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_flushms{}/px_pool_stats_num_flushes{}",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "PX Pool Flush Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_flushed_bytes{}/(px_pool_stats_flushms{}/1000)",
     "legendFormat": "{{node}}_{{pool}}"
    }
   ]
  },
  {
   "title": "IO Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "px_volume_dev_depth_io{}", "legendFormat": "{{instance}}_{{volumeid}}" }
   ]
  },
  {
   "title": "Aggregate Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(px_disk_stats_written_bytes[1m]))",
     "legendFormat": "pool"
    },
    {
     "expr": "sum(px_volume_writethroughput{})",
     "legendFormat": "volume"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m]))",
     "legendFormat": "px device"
    },
    {
     "expr": "sum(rate(px_disk_stats_written_bytes[1m]))/sum(rate(node_disk_written_bytes_total{device=~\".+pxd.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Long IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_writes{}", "legendFormat": "{{node}}_{{volumeid}}" },
    { "expr": "-(px_volume_num_long_reads{})", "legendFormat": "{{node}}_{{volumeid}}" }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } }
 ]
}